### ISSUE TITLE
Api url fails badly

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#126]
https://api.jarr.info/swagger
![image](https://user-images.githubusercontent.com/1086629/81485673-43747a00-924f-11ea-90c3-cd6b7fb65570.png)

**Comment by jaesivsm** [comment]
God this one made my brain hurt.
Basically flask doesn't take `PREFERRED_SCHEME` config option into account when generating the url for the swagger json because it's generated at load time and not in a request context. It's a bug from the flask-restx library I'd say. 

Thanks for reporting !
