### ISSUE TITLE
Refresh feed list should refresh article list

### ISSUE THREAD

**Issue by durable-server** [jaesivsm/JARR#18]
Use case:

Go on a feed to see its listed items.
Click the refresh bouton at the top.
If there is new items in the feed, the count will be updated next to the feed name (left column), but the feed list won't (center column).

**Comment by blatinier** [comment]
Sorry, I posted the issue with the wrong account…

**Comment by jaesivsm** [comment]
That issue was actually resolved some time ago but I totally forgot to mark it so. Here we go...
