### ISSUE TITLE
Feed category edition fails

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#21]
On the main board, when editing a feed to change its category, the update fails.
Ajax call seems good however (see the PUT payload below) : 

`{"title":"xkcd.com","description":"xkcd.com: A webcomic of romance and math humor.","link":"http://xkcd
.com/rss.xml","site_link":"http://xkcd.com/","enabled":true,"readability_auto_parse":false,"filters"
:[],"category_id":"19"}`

**Comment by jaesivsm** [comment]
Yeah, I think it's related to the recent rework on edition rights for the API which the first page uses. Gonna look into it tonight.
