### ISSUE TITLE
unread counter are buggy

### ISSUE THREAD

**Issue by jaesivsm** [jaesivsm/JARR#24]

**Comment by blatinier** [comment]
Buggy usecase: 
Having a feed with a removed item with autoreadability.
When clicking on the item to read it, loading fails, counter doesn't decrement but item is marked as read. (1 in counter for 0 articles)
Setting the item back has unread increment again the counter (2 in counter for 1 article)

You can play this scenario again to have a bigger counter with just one article.

**Comment by jaesivsm** [comment]
moving that issue to next release, unless some major usecase where counter fails are discovered

**Comment by jaesivsm** [comment]
will be redone with the new UI
