### ISSUE TITLE
Truncate very long titles in the item presentation component (or enlarge header height)

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#25]
When the item has a very long title (97 chars on my screen for exemple) the icons in the header on the item presentation component (the one at the right) go out of the header.

A solution is to truncate the titles around 80 chars (which works for me but not for everyone I think)
Maybe some css magic can work here.

Another solution is to set the header to the right height which is not really pretty I think.

**Comment by jaesivsm** [comment]
I'd prefer not to truncate title because there is no other way to read it and certain feed provide most of their text through their title. The title could be repeated below but I feel it would seem uneasy on the eye.

I'd prefer the style solution (fixing icons on top or something similar).

**Comment by blatinier** [comment]
Some CSS like this seems to work for me:
`<img width="16px" src="FEED-ICON" style="position: absolute; padding-top: 3px">
<span style="display: inline-block; width: 80%; padding-left: 20px;">LONG TITLE</span>`

Explanations:
The buttons at the right need place → span `width: 80%` + `display: inline-block` so that width has effect (maybe using a div instead does the trick too)
After that the feed icon is not well placed. `position: absolute` make its position absolute to the parent block (so it doesn't get moved around by block magics) the `padding-top` center it on the line.
Finally the `padding-left` on the span leave space for the feed icon.
