### ISSUE TITLE
Add title attribute to buttons

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#26]
Buttons have no title attributes thus you have no clue on what a bouton does if you don't understand the icon.

Adding one will display some more information on mouse rollover which is nice.

**Comment by jaesivsm** [comment]
Missing title on right panel for :
* delete button 
* redability button 
* edit button

**Comment by jaesivsm** [comment]
Has been resolved in the master version. Bunch of links are now available in the "About" page.
