### ISSUE TITLE
Multiple undue notifications

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#41]
Use case:
- Add some new feeds
- Then add a new category
- You are redirected to a page for editing the newly created category (see #28  for my toughs on this page) with feed creations success.

The probable reason is that flash messages are flushed only there since feed creation is full Ajax
A solution would be to not record a flash message on feed creation.

**Comment by jaesivsm** [comment]
Yep, this is due flash message accumulating in the background and never getting to be displayed. 
It's not really nice but it should be will be resolved by #16
