### ISSUE TITLE
Can't add feed

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#55]
When I try to add this feed:
https://www.youtube.com/channel/UCXGrPbB-bmAOr_DpI29Phzw/videos
I get a 500 error in the console (and nothing in the UI).

**Comment by jaesivsm** [comment]
Sorry about that and thanks for reporting it. Fixed in prod, i'll publish a patch later. 

The whole thing was due to some code improving feed construction which is still ongoing testing.
