### ISSUE TITLE
refetch on expire or max-age

### ISSUE THREAD

**Issue by jaesivsm** [jaesivsm/JARR#56]
We should respect the server indication about when to re-fetch a feed. It provides it through the HTTP [Expires](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21) header or the [max-age](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.3) property in a cache control header.

An expire feed should be added to the feed table and the date comparison should be made on it.

**Comment by da2x** [comment]
Note that max-age and etags should also be processed and updated for some none successful statuses such as 204 and 304 as well.

**Comment by jaesivsm** [comment]
Thanks ! That's true ! And it has been taken care of (for [204](https://github.com/jaesivsm/JARR/blob/develop/src/crawler/http_crawler.py#L159) and [304](https://github.com/jaesivsm/JARR/blob/develop/src/crawler/http_crawler.py#L200)). That'll soon hit the master branch.
