### ISSUE TITLE
www.jarr.info going on 404 instead of 301 to jarr.info

### ISSUE THREAD

**Issue by blatinier** [jaesivsm/JARR#57]
Jarr should work with www.jarr.info (at least redirect to the naked domain).

Note: There is a real question about should we use naked domains to serve websites as they does not support CNAME entries in the DNS and that CNAME entries are one of the main method used to loadbalance.
See http://www.yes-www.org/why-use-www/

**Comment by jaesivsm** [comment]
Fixed with v3, thanks for the idea a while back by the way !!

**Comment by blatinier** [comment]
Damn you went back in history there! :o

**Comment by jaesivsm** [comment]
Yeah took the time x)
