### ISSUE TITLE
Localizaition: Switch from middle- to big-endian date format (remove Americanism)

### ISSUE THREAD

**Issue by da2x** [jaesivsm/JARR#62]
Only the US uses a middle-endian date format, and most of the world uses a little-endian format. The international standard date format says to use only the big-to-little endian format. ([World date-format map](https://en.wikipedia.org/wiki/Date_format_by_country#map).)

Similarly, most of the world uses a 24-hour clock (HH:MM with leading zero) [instead of the 12-hour clock](http://www.talkstandards.com/wp-content/uploads/2011/02/12-hour-clock.jpeg) and the ISO 8601 standard agrees that this is the preferred clock presentation.

Suggested format: **YYYY-mm-dd HH:MM** (big-middle-little hour:minutes, from ISO 8601)

Disclosure: I’m [biased](https://ctrl.blog/entry/date-formats-web) for the standardized date format.

**Comment by jaesivsm** [comment]
I have to read up a bit on this but I use the babel format datetime and format timedelta to display those kind of things. 

It'll have to go through a user preference setting but I also think something is broken with the localization guessing.

**Comment by da2x** [comment]
> something is broken with the localization guessing.

The only thing that is broken is the fact that you’re guessing the locale. Regardless of where you buy hardware in the world, a lot of devices will have an Accept-Language header that either begins with or contains `en-US`. Not all operating systems/devices come with locale languages, and the default language / locale is very often en-US. If you want a default use `D. m Y` as this is the correct option for most of the world (refer to the above world map).

If you really need to guess the locale locale, then use geolocation and set the locale by country instead. This should have a much higher level of accuracy than HTTP headers.

**Comment by jaesivsm** [comment]
> The only thing that is broken is the fact that you’re guessing the locale. 

I'd say it's the more the fact that I'm defaulting to `en-US`. It's actually Babel that miss some languages, it's working fine with French but I found it was defaulting to `en-US` when trying with different languages. 
I'll try updating it see if I can include more languages.

> If you really need to guess the locale, then use geolocation and set the locale by country instead. This should have a much higher level of accuracy than HTTP headers.

Guessing locale through geoip seems wrong as you may not want the main language of where you're request originate.
Setting the language you want in your browser, which will pass it in the headers, should be the way to go. Again it works with French and it should work with other languages.

A good fix would be to be able to override that with some user setting. But if babel is missing the languages, there's not much I can do.

**Comment by jaesivsm** [comment]
I added to the develop branch a better support for local and default to en_GB which should provide some non MM/DD/YYYY date or AM/PM non sense for those who don't provide Accept-Language header.
