### ISSUE TITLE
Weird icon choises

### ISSUE THREAD

**Issue by da2x** [jaesivsm/JARR#63]
“Mark all as read”: trash can

“Delete feed”: an X

This seems somewhat backwards. “Mark all as read” is usually a checkmark on a list (interpose **≡✓** with the checkmark offset halfway to the left).

<img width="1440" alt="toolbar" src="https://cloud.githubusercontent.com/assets/1102886/21051628/867dbbc8-be21-11e6-844c-46d978c83b91.png">

Secondarily: the leftmost icons are horizontally uneaven with the icons on the right.

**Comment by jaesivsm** [comment]
I switched the two icons. Thanks for the comment on the style.

Concerning alignment it is because panels do not share a common navbar which would require a bigger rework on the UI, so yeah, maybe later.
