### ISSUE TITLE
release blocker

### ISSUE THREAD

**Issue by jaesivsm** [jaesivsm/JARR#67]
# UI Fixes
- [x] feed option: change "Auto readability" to "Auto parsing" and add an help text
- [x] category option: change "Allow Clustering on title" to "Cluster on title" and add an help text

# Other
- [ ] Fill the documentation
- [ ] code reorganisation, split ```server```, ```ui```, ```crawler``` and ```shared```

**Comment by da2x** [comment]
(Pst: Use the milestone feature in GitHub to track release blockers.)

**Comment by jaesivsm** [comment]
(yeah, at the time I guess I wanted to regroup small fixes that may not require an entire issue for them)
